# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APP',
            new_name='PracticalTest',
        ),
    ]
