# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_remove_group__is_closed'),
        ('exam', '0002_auto_20180123_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['created_at'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='grat',
            options={'ordering': ['created_at'], 'verbose_name': 'gRAT', 'verbose_name_plural': 'gRAT'},
        ),
        migrations.AlterModelOptions(
            name='irat',
            options={'ordering': ['created_at'], 'verbose_name': 'iRAT', 'verbose_name_plural': 'iRAT'},
        ),
        migrations.RemoveField(
            model_name='grat',
            name='group',
        ),
        migrations.RemoveField(
            model_name='irat',
            name='student',
        ),
        migrations.RemoveField(
            model_name='practicaltest',
            name='score',
        ),
        migrations.AddField(
            model_name='grat',
            name='groups',
            field=models.ManyToManyField(to='groups.Group', verbose_name='gRATs'),
        ),
        migrations.AddField(
            model_name='irat',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='iRATs'),
        ),
    ]
