# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180123_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 2, 18, 56, 280619, tzinfo=utc), help_text='Date and time to provide the test to be answered.', verbose_name='Date and time to provide the test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.TimeField(help_text='Time to answer the test.', verbose_name='Time to answer.'),
        ),
    ]
