# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180124_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irat',
            name='students',
        ),
        migrations.AlterField(
            model_name='exam',
            name='datetime',
            field=models.DateTimeField(help_text='Date and time to provide the test to be answered.', verbose_name='Provide the test'),
        ),
    ]
