# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20180124_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='Exam questions'),
        ),
    ]
