# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0006_auto_20180124_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='irat',
            name='students',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='iRATs'),
        ),
        migrations.AlterField(
            model_name='grat',
            name='groups',
            field=models.ManyToManyField(null=True, to='groups.Group', verbose_name='gRATs'),
        ),
    ]
