# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20180124_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AlterField(
            model_name='exam',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBLSessions.TBLSession', verbose_name='exams'),
        ),
    ]
