# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20180124_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TBLSessions.TBLSession'),
        ),
    ]
