# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group__is_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TBLSessions', '0004_auto_20180115_2339'),
        ('exam', '0011_auto_20180124_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='session',
        ),
        migrations.RemoveField(
            model_name='grat',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='irat',
            name='students',
        ),
        migrations.AddField(
            model_name='grat',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.Group', verbose_name='gRATs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grat',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TBLSessions.TBLSession', verbose_name='gRATs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irat',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TBLSessions.TBLSession', verbose_name='iRATs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irat',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='iRATs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.TimeField(default='40:00', help_text='Time to answer the test.', verbose_name='Time to answer'),
        ),
    ]
