# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20180124_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grat',
            old_name='session',
            new_name='tbl_session',
        ),
        migrations.RenameField(
            model_name='irat',
            old_name='session',
            new_name='tbl_session',
        ),
    ]
