# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20180124_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.PositiveIntegerField(default=40, help_text='Time to answer the test in minutes.', verbose_name='Time to answer'),
        ),
    ]
