# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20180124_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group', verbose_name='gRATs'),
        ),
        migrations.AlterField(
            model_name='irat',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='iRATs'),
        ),
    ]
