# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20180124_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gRATs', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='grat',
            name='tbl_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gRATs', to='TBLSessions.TBLSession'),
        ),
        migrations.AlterField(
            model_name='irat',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iRATs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='irat',
            name='tbl_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iRATs', to='TBLSessions.TBLSession'),
        ),
    ]
