# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.FloatField(default=0.0, help_text='results of group info.', verbose_name='results')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_info', to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='disciplines.Discipline', verbose_name='Discipline')),
            ],
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankingGroup.Ranking'),
        ),
    ]
