from .discipline_file.create_view import DisciplineFileCreateView
from .discipline_file.delete_view import DisciplineFileDeleteView
from .discipline_file.list_view import DisciplineFileListView
from .discipline_file.update_view import DisciplineFileUpdateView
from .module_file.create_view import ModuleFileCreateView
from .module_file.delete_view import ModuleFileDeleteView
from .module_file.list_view import ModuleFileListView
from .module_file.update_view import ModuleFileUpdateView
