# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TBLSessions', '0003_auto_20180102_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Alternative title.', max_length=500, verbose_name='Title')),
                ('score', models.PositiveIntegerField(help_text='Alternative score.', verbose_name='Score')),
                ('is_correct', models.BooleanField(default=False, help_text='Is correct alternative to answer the question.', verbose_name='Is correct?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the alternative of question is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the alternative of question is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Alternatives',
                'verbose_name': 'Alternative',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Question title.', max_length=100, verbose_name='Title')),
                ('level', models.CharField(choices=[('Intermediary', 'Intermediary'), ('Basic', 'Basic'), ('Advanced', 'Advanced')], help_text='Difficulty level', max_length=15, verbose_name='Level')),
                ('topic', models.CharField(help_text='Question topic.', max_length=100, verbose_name='Topic')),
                ('score', models.PositiveIntegerField(help_text='Question score.', verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the question is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the question is updated.', verbose_name='Updated at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBLSessions.TBLSession', verbose_name='questions')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'verbose_name': 'Question',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='questions.Question'),
        ),
    ]
