# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_exercise',
            field=models.BooleanField(default=True, help_text='Exercise are questions that appear in the exercise list.', verbose_name='Is it an exercise?'),
        ),
        migrations.AddField(
            model_name='question',
            name='show_answer',
            field=models.BooleanField(default=False, help_text='Show answer about the specific question', verbose_name='Show question answer.'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Alternative score.', verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('intermediary', 'Intermediary')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Question score.', verbose_name='Score'),
        ),
    ]
