# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180108_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='alternative_title',
            field=models.CharField(help_text='Alternative title.', max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Intermediary', 'Intermediary'), ('Advanced', 'Advanced'), ('Basic', 'Basic')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
    ]
