# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180108_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='alternative_title',
            field=models.CharField(help_text='Alternative title.', max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='score',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, help_text='Alternative score.', verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Intermediary', 'Intermediary'), ('Basic', 'Basic'), ('Advanced', 'Advanced')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Question title.', max_length=1000, verbose_name='Title'),
        ),
    ]
