# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20180115_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='current_page',
            field=models.CharField(default='1', help_text='Store the current question page.', max_length=50, verbose_name='Current page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Intermediary', 'Intermediary')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
    ]
