# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0015_auto_20180124_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_alternative', models.CharField(help_text='Correct alternative title.', max_length=1000, verbose_name='Correct Alternative')),
                ('exam', models.CharField(choices=[('iRAT', 'iRAT'), ('gRAT', 'gRAT'), ('Exercise', 'Exercise')], default='Exercise', max_length=10)),
                ('score', models.PositiveIntegerField(default=0, help_text='Question score answered.', verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the submission of question is created.', verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Submissions',
                'ordering': ['user', 'exam', 'question', 'created_at'],
                'verbose_name': 'Submission',
            },
        ),
        migrations.AlterModelOptions(
            name='alternative',
            options={'ordering': ['title', 'created_at'], 'verbose_name': 'Alternative', 'verbose_name_plural': 'Alternatives'},
        ),
        migrations.RenameField(
            model_name='alternative',
            old_name='alternative_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='alternative',
            name='score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Intermediary', 'Intermediary')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TBLSessions.TBLSession'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questions.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
