# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20180124_0136'),
        ('questions', '0015_auto_20180124_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.iRAT', verbose_name='questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Intermediary', 'Intermediary'), ('Advanced', 'Advanced'), ('Basic', 'Basic')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
    ]
