# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20180125_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correct_alternative',
            field=models.CharField(default='', help_text='Correct alternative title.', max_length=1000, verbose_name='Correct Alternative'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Basic', 'Basic'), ('Intermediary', 'Intermediary')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
    ]
