# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_remove_group__is_closed'),
        ('questions', '0027_auto_20180203_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Submission')),
            ],
            options={
                'ordering': ['user', 'question', 'created_at'],
                'verbose_name': 'Exercise Submission',
                'verbose_name_plural': 'Exercise Submissions',
            },
            bases=('questions.submission',),
        ),
        migrations.CreateModel(
            name='GRATSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Submission')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='groups.Group', verbose_name='Groups')),
            ],
            options={
                'ordering': ['group', 'question', 'created_at'],
                'verbose_name': 'gRAT Submission',
                'verbose_name_plural': 'gRAT Submissions',
            },
            bases=('questions.submission',),
        ),
        migrations.CreateModel(
            name='IRATSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Submission')),
            ],
            options={
                'ordering': ['user', 'question', 'created_at'],
                'verbose_name': 'iRAT Submission',
                'verbose_name_plural': 'iRAT Submissions',
            },
            bases=('questions.submission',),
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Intermediary', 'Intermediary')], default='basic', help_text='Difficulty level', max_length=15, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='iratsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irat_submissions', to='questions.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='iratsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irat_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='gratsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grat_submissions', to='questions.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to='questions.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
