# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Classroom title.', max_length=100, verbose_name='Title')),
                ('password', models.CharField(help_text='Password to get into the class.', max_length=30, verbose_name='Password')),
                ('student_limit', models.PositiveIntegerField(default=0, help_text='Student limit to getin into the class.', verbose_name='Student limit')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='disciplines.Discipline', verbose_name='Discipline')),
                ('monitors', models.ManyToManyField(related_name='monitor_classes', to=settings.AUTH_USER_MODEL, verbose_name='Monitors')),
                ('students', models.ManyToManyField(related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['title'],
            },
        ),
    ]
