# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0002_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='monitors',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AddField(
            model_name='discipline',
            name='classroom',
            field=models.CharField(default=1, help_text='Classroom title of discipline.', max_length=10, verbose_name='Classroom title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='monitors',
            field=models.ManyToManyField(related_name='monitor_classes', to=settings.AUTH_USER_MODEL, verbose_name='Monitors'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='password',
            field=models.CharField(default=1, help_text='Password to get into the class.', max_length=30, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='student_limit',
            field=models.PositiveIntegerField(default=0, help_text='Student limit to getin into the class.', verbose_name='Student limit'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
