# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0003_auto_20171025_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(help_text='Discipline description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='monitors',
            field=models.ManyToManyField(blank=True, related_name='monitor_classes', to=settings.AUTH_USER_MODEL, verbose_name='Monitors'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
