# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0004_auto_20171025_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='password',
            field=models.CharField(blank=True, help_text='Password to get into the class.', max_length=30, verbose_name='Password'),
        ),
    ]
