# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0005_auto_20171027_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Close discipline.', verbose_name='Is closed?'),
        ),
    ]
