# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0007_auto_20171027_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='student_limit',
            new_name='students_limit',
        ),
    ]
