# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0008_auto_20171028_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='classroom',
            field=models.CharField(help_text='Classroom title of discipline.', max_length=10, verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut'),
        ),
    ]
