# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 19:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0009_auto_20171030_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='students_limit',
            field=models.PositiveIntegerField(default=0, help_text='Students limit to get in the class.', validators=[django.core.validators.MaxValueValidator(60, 'There can be no more than %(limit_value)s students in the class.'), django.core.validators.MinValueValidator(5, 'Must have at least %(limit_value)s students in class.')], verbose_name='Students limit'),
        ),
    ]
