# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 03:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0011_auto_20171102_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='monitors_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monitors limit to insert in the class.', validators=[django.core.validators.MaxValueValidator(5, 'There can be no more than %(limit_value)s monitors in the class.'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to %(limit_value)s.')], verbose_name='Monitors limit'),
        ),
    ]
