# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 20:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0012_auto_20171207_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='classroom',
            field=models.CharField(help_text='Classroom title of discipline.', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^Class|^Turma [A-Z]$', 32), "Enter a valid classroom, the classroom need to be 'Class A-Z'")], verbose_name='Classroom'),
        ),
    ]
