# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0013_auto_20171211_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='was_group_provided',
            field=models.BooleanField(default=False, help_text='Provide groups to students see.', verbose_name='Was group provided?'),
        ),
    ]
