# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1, max_length=100, verbose_name='Identify'),
            preserve_default=False,
        ),
    ]
