# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171004_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='important', max_length=100, verbose_name='Identify'),
            preserve_default=False,
        ),
    ]
