# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tags', to='core.Tag'),
        ),
    ]
