# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hallOfFame.models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
        ('hallOfFame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=hallOfFame.models.current_year, verbose_name='year')),
                ('semester', models.IntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='disciplines.Discipline')),
            ],
        ),
        migrations.DeleteModel(
            name='TBLSession',
        ),
    ]
