# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankingGroup', '0001_initial'),
        ('hallOfFame', '0002_auto_20180525_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='group_info',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='rankingGroup.GroupInfo'),
        ),
    ]
