from .practical_test_detail_view import PracticalTestDetailView
from .practical_test_update_view import PracticalTestUpdateView
from .tbl_session_create_view import TBLSessionCreateView
from .tbl_session_delete_view import TBLSessionDeleteView
from .tbl_session_detail_view import TBLSessionDetailView
from .tbl_session_update_view import TBLSessionUpdateView
from .tbl_session_list_view import TBLSessionListView
