# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0014_discipline_was_group_provided'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the session is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the session is updated.', verbose_name='Updated at')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='disciplines.Discipline', verbose_name='Disciplines')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_grades', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
            ],
            options={
                'verbose_name_plural': 'Discipline grades',
                'verbose_name': 'Discipline grades',
                'ordering': ['discipline', 'student', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['session', 'student', 'created_at'], 'verbose_name': 'TBL Session grades', 'verbose_name_plural': 'TBL Sessions grades'},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_grades', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
            preserve_default=False,
        ),
    ]
