# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, help_text='Short name that will be used uniquely on the platform.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'Enter a valid username', 'This value should only contain letters, numbers,                   and characters @/./+/-/_.', 'invalid')], verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Full user name.', max_length=150, verbose_name='Name'),
        ),
    ]
