from .group_create_view import GroupCreateView
from .group_delete_view import GroupDeleteView
from .group_list_view import GroupListView
from .group_provide_view import GroupProvideView
from .group_update_view import GroupUpdateView
from .student_insert_view import StudentInsertView
from .student_remove_view import StudentRemoveView
from .student_list_available_view import StudentListAvailableView
