# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0014_discipline_was_group_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='TBL session description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('is_closed', models.BooleanField(default=False, help_text='Close discipline.', verbose_name='Is closed?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the discipline is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the discipline is updated.', verbose_name='Updated at')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbl_sessions', to='disciplines.Discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'TBL Session',
                'verbose_name_plural': 'TBL Sessions',
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
