# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBLSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='TBL session description.', verbose_name='Description')),
                ('is_closed', models.BooleanField(default=False, help_text='Close TBL session.', verbose_name='Is closed?')),
                ('irat_datetime', models.DateTimeField(blank=True, help_text='Date and time to provide the iRAT test.', null=True, verbose_name='iRAT date')),
                ('irat_weight', models.PositiveIntegerField(blank=True, default=3, help_text='iRAT test weight.', verbose_name='iRAT weight')),
                ('irat_duration', models.PositiveIntegerField(blank=True, default=30, help_text='iRAT duration in minutes to be answered.', verbose_name='iRAT durantion in minutes')),
                ('grat_datetime', models.DateTimeField(blank=True, help_text='Date and time to provide the gRAT test.', null=True, verbose_name='gRAT date')),
                ('grat_weight', models.PositiveIntegerField(blank=True, default=2, help_text='gRAT test weight.', verbose_name='gRAT test weight')),
                ('grat_duration', models.PositiveIntegerField(blank=True, default=30, help_text='gRAT duration in minutes to be answered.', verbose_name='gRAT durantion in minutes')),
                ('practical_available', models.BooleanField(default=False, help_text='Release the practical test.', verbose_name='Release the practical test')),
                ('practical_weight', models.PositiveIntegerField(blank=True, default=4, help_text='Practical test weight.', verbose_name='Practical test weight')),
                ('practical_description', models.TextField(help_text='Practical test description.', verbose_name='Description')),
                ('peer_review_available', models.BooleanField(default=False, help_text='Release the peer review test to be answered.', verbose_name='Release the peer review test')),
                ('peer_review_weight', models.PositiveIntegerField(blank=True, default=1, help_text='Peer review weight.', verbose_name='Peer review weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the session is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the session is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'TBL Session',
                'ordering': ['title', 'created_at'],
                'verbose_name_plural': 'TBL Sessions',
            },
        ),
    ]
