# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
        ('TBLSessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsession',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbl_sessions', to='disciplines.Discipline', verbose_name='Discipline'),
        ),
    ]
