# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsession',
            name='slug',
        ),
    ]
