# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0004_auto_20180115_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsession',
            name='grat_available',
            field=models.BooleanField(default=False, help_text='Release the gRAT test to be answered.', verbose_name='Release the gRAT test'),
        ),
        migrations.AddField(
            model_name='tblsession',
            name='grat_duration',
            field=models.PositiveIntegerField(default=40, help_text='gRAT duration in minutes to be answered.', verbose_name='gRAT durantion in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsession',
            name='irat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 23, 30, 5, 414432, tzinfo=utc), help_text='Date and time to provide the iRAT test.', verbose_name='iRAT date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsession',
            name='irat_duration',
            field=models.PositiveIntegerField(default=40, help_text='iRAT duration in minutes to be answered.', verbose_name='iRAT durantion in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsession',
            name='peer_review_available',
            field=models.BooleanField(default=False, help_text='Release the peer review test to be answered.', verbose_name='Release the peer review test'),
        ),
        migrations.AddField(
            model_name='tblsession',
            name='practical_available',
            field=models.BooleanField(default=False, help_text='Release the practical test.', verbose_name='Release the practical test'),
        ),
    ]
