# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0005_auto_20180127_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsession',
            name='grat_duration',
            field=models.PositiveIntegerField(default=30, help_text='gRAT duration in minutes to be answered.', verbose_name='gRAT durantion in minutes'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='irat_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time to provide the iRAT test.', null=True, verbose_name='iRAT date'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='irat_duration',
            field=models.PositiveIntegerField(default=30, help_text='iRAT duration in minutes to be answered.', verbose_name='iRAT durantion in minutes'),
        ),
    ]
