# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0008_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['session', 'user', 'created_at'], 'verbose_name': 'TBL Session grades', 'verbose_name_plural': 'TBL Sessions grades'},
        ),
        migrations.AddField(
            model_name='grade',
            name='grat_weight',
            field=models.PositiveIntegerField(default=2, help_text='gRAT test weight.', verbose_name='gRAT test weight'),
        ),
        migrations.AddField(
            model_name='grade',
            name='irat_weight',
            field=models.PositiveIntegerField(default=3, help_text='iRAT test weight.', verbose_name='iRAT weight'),
        ),
        migrations.AddField(
            model_name='grade',
            name='peer_review_weight',
            field=models.PositiveIntegerField(default=1, help_text='Peer review weight.', verbose_name='Peer review weight'),
        ),
        migrations.AddField(
            model_name='grade',
            name='practical_weight',
            field=models.PositiveIntegerField(default=4, help_text='Practical test weight.', verbose_name='Practical test weight'),
        ),
    ]
