# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0009_auto_20180129_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grat_weight',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='irat_weight',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='peer_review_weight',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='practical_weight',
        ),
        migrations.AddField(
            model_name='tblsession',
            name='grat_weight',
            field=models.PositiveIntegerField(default=2, help_text='gRAT test weight.', verbose_name='gRAT test weight'),
        ),
        migrations.AddField(
            model_name='tblsession',
            name='irat_weight',
            field=models.PositiveIntegerField(default=3, help_text='iRAT test weight.', verbose_name='iRAT weight'),
        ),
        migrations.AddField(
            model_name='tblsession',
            name='peer_review_weight',
            field=models.PositiveIntegerField(default=1, help_text='Peer review weight.', verbose_name='Peer review weight'),
        ),
        migrations.AddField(
            model_name='tblsession',
            name='practical_weight',
            field=models.PositiveIntegerField(default=4, help_text='Practical test weight.', verbose_name='Practical test weight'),
        ),
    ]
