# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0010_auto_20180129_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='session_score',
        ),
    ]
