# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0011_remove_grade_session_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsession',
            name='practical_description',
            field=models.TextField(default='', help_text='Practical test description.', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
