# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0012_tblsession_practical_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='session',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
