# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0013_auto_20180203_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsession',
            name='practical_description',
            field=models.TextField(blank=True, help_text='Practical test description.', verbose_name='Description'),
        ),
    ]
