# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0014_auto_20180203_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsession',
            name='grat_duration',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='gRAT duration in minutes to be answered.', verbose_name='gRAT durantion in minutes'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='grat_weight',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='gRAT test weight.', verbose_name='gRAT test weight'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='irat_duration',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='iRAT duration in minutes to be answered.', verbose_name='iRAT durantion in minutes'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='irat_weight',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='iRAT test weight.', verbose_name='iRAT weight'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='peer_review_weight',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Peer review weight.', verbose_name='Peer review weight'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='practical_description',
            field=models.TextField(help_text='Practical test description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tblsession',
            name='practical_weight',
            field=models.PositiveIntegerField(blank=True, default=4, help_text='Practical test weight.', verbose_name='Practical test weight'),
        ),
    ]
