# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
        ('TBLSessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of file.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of file.', max_length=500, verbose_name='Description')),
                ('extension', models.CharField(help_text='File extension.', max_length=10, verbose_name='File extension')),
                ('archive', models.FileField(upload_to='disciplines/files', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the file is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the file is updated', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'File',
                'ordering': ['title', 'created_at'],
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='DisciplineFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.File')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='disciplines.Discipline', verbose_name='Discipline')),
            ],
            bases=('files.file',),
        ),
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.File')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='TBLSessions.TBLSession', verbose_name='Session')),
            ],
            bases=('files.file',),
        ),
    ]
