# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0014_discipline_was_group_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of file.', max_length=50, verbose_name='Title')),
                ('extension', models.CharField(help_text='File extension.', max_length=10, verbose_name='File extension')),
                ('archive', models.FileField(upload_to='disciplines/files', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the file is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the file is updated', verbose_name='Updated at')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='disciplines.Discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
