# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(default=1, help_text='Description of file.', max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
