# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBLSessions', '0002_remove_tblsession_slug'),
        ('files', '0002_file_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.File')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='TBLSessions.TBLSession', verbose_name='Session')),
            ],
            bases=('files.file',),
        ),
    ]
