# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_sessionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.File')),
            ],
            bases=('files.file',),
        ),
    ]
