# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_disciplinefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(help_text='Title of file.', max_length=200, verbose_name='Title'),
        ),
    ]
