# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171211_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='is_closed',
            new_name='_is_closed',
        ),
    ]
