# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20171212_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='_is_closed',
        ),
    ]
