# TESTS --------------------------------------------------------
folder := pgtbl

test: coverage report xml

coverage:
	# Execute all tests
	coverage run --source="." pgtbl/manage.py test ${folder}

report:
	# Show coverage on terminal
	coverage report -m

html:
	# Generate coverage html
	coverage html

xml:
	# Generate coverage xml
	coverage xml

codacy:
	# Insert coverage into codacy
	python-codacy-coverage -r coverage.xml

clean:
	# Remove the html generated by coverage
	rm -rf ./htmlcov/
