# TESTS --------------------------------------------------------
folder := pgtbl

test: coverage report xml

coverage:
	# Execute all tests
	sudo docker-compose exec pgtbl coverage run --source="." pgtbl/manage.py test ${folder}

report:
	# Show coverage on terminal
	sudo docker-compose exec pgtbl coverage report -m

html:
	# Generate coverage html
	sudo docker-compose exec pgtbl coverage html

xml:
	# Generate coverage xml
	sudo docker-compose exec pgtbl coverage xml

codacy:
	# Insert coverage into codacy
	sudo docker-compose exec pgtbl python-codacy-coverage -r coverage.xml

clean:
	# Remove the html generated by coverage
	sudo docker-compose exec pgtbl rm -rf ./htmlcov/
