# TESTS --------------------------------------------------------
tests_folder := pgtbl/**/tests/

test: coverage report html

coverage:
	# Execute all tests
	coverage run --source="." pgtbl/manage.py test ${tests_folder}

report:
	# Show coverage on terminal
	coverage report -m

html:
	# Generate coverage html
	coverage html

clean:
	# Remove the html generated by coverage
	rm -rf ./htmlcov/
