from .apps import PRODUCTION_APPS, DEVELOPMENT_APPS
from .database import SQLITE, POSTGRES
from .password import AUTH_PASSWORD_VALIDATORS
from .middleware import MIDDLEWARE
from .template import TEMPLATES
from .security import SECRET_KEY
from .messages import MESSAGE_TAGS
from .files import (
    STATIC_ROOT, MEDIA_ROOT, STATIC_URL, MEDIA_URL
)
from .email import (
    DEFAULT_FROM_EMAIL, EMAIL_USE_TLS, EMAIL_HOST, EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD, EMAIL_PORT, EMAIL_BACKEND
)
from .user import (
    AUTH_USER_MODEL, LOGIN_URL, LOGOUT_URL, LOGIN_REDIRECT_URL,
    AUTHENTICATION_BACKENDS
)
from .internacionalization import (
    DEFAULT_LANGUAGE, SAO_PAULO, USA, INTERNATIONALIZATION,
    FORMAT_DATES, TIMEZONE_DATETIMES, LANGUAGES
)